language: go

os:
    - osx
    - linux

before_install:
  - go get golang.org/x/lint/golint
  - go mod tidy

script:
  - go vet ./...
  - golint ./...
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
  - golangci-lint run
  - go test -tags skipsecretserviceintegrationtests ./...

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
